### ISSUE TITLE
USER STORY: Site Navigation

### ISSUE THREAD

**Issue by morganoleary** [morganoleary/Fine-Furnishings#1]
As a **first time user** I can **easily navigate the site** so that **I can learn about what the company has to offer**.

## Acceptance Criteria:
- The site will have a clear color scheme & styles for easy viewing. 
- The menu bar should be easily visible/accessible to the user.
- This will be located next to the logo.
- This will be a hamburger menu on mobile devices.

## Tasks:
- [x] Set color scheme and fonts for site
- [x] Create the navigation bar in base template
- [x] Implement a hamburger dropdown menu for mobile devices
