### ISSUE TITLE
USER STORY: User Account - Delete Account

### ISSUE THREAD

**Issue by morganoleary** [morganoleary/Fine-Furnishings#10]
As a **returning visitor** I can **login to my account** so that **I can delete my account with the company** . 

## Acceptance Criteria:
- Once logged in the menu options will change and the user will be able to click on "Personal Details".
- On this page, the user will have the option to delete their account.
- When this button is clicked, the user will receive a warning before confirming deletion of their account.
- Deleting an account will clear all details of the user to the site (wishlist, order history, personal details).

## Tasks:
- [x] Create a "Delete Account" button on the Personal Details page
- [x] Implement a pop-up warning to confirm deletion
- [x] Delete all account details visible to the user
