### ISSUE TITLE
USER STORY: Admin - Products

### ISSUE THREAD

**Issue by morganoleary** [morganoleary/Fine-Furnishings#14]
As a **site owner** I can **update product details** so that **I can manage items available to customers** . 

## Acceptance Criteria:
- The product section will contain the details of each product.
- Product details will include: name, image, sku / ID, price, delivery charge (if applicable), description, dimensions & categories.

## Tasks:
- [x] Implement a products section in the admin dashboard
- [x] Store product details including: name, image, sku / ID, price, description, dimensions & categories
- [x] Ensure the site owner can update product details
