### ISSUE TITLE
USER STORY: Contact Form - Send general queries

### ISSUE THREAD

**Issue by morganoleary** [morganoleary/Fine-Furnishings#16]
As a **first time user** I can **send queries to the business** so that **I can find out more about them** . 

## Acceptance Criteria:
- This page can be found from a link in the footer and will include a contact form to contact the business. 
- This form will include: name, mobile #, email address, text box to enter query (with placeholder text) & a dropdown option to select the reason for the query. 
- A submit button will be located below the form to allow the user to send the query. 
- Confirmation of submission will appear to the user. 
- This page will be accessible from the FAQs page to allow the user to easily ask a question (if not answered in the FAQs).

## Tasks:
- [x] Add a 'Contact Us' link in the footer that will appear on all pages of the site
- [x] Ensure the contact form contact the following fields: name, phone number, email, text input box and a dropdown menu with a 'general query' option
- [x] Include a 'Submit' button below the contact form that will send the query to the admin site
- [x] Once submitted, implement a success message to the user that the message was sent
- [x] Include a link to the 'contact us' page on the FAQs page
