### ISSUE TITLE
USER STORY: Contact Form - Returns

### ISSUE THREAD

**Issue by morganoleary** [morganoleary/Fine-Furnishings#17]
As a **user** I can **send queries to the business** so that **I can learn how to return an order** . 

## Acceptance Criteria:
- The 'Contact Us' page will be accessible from a link in the footer.
- The contact form dropdown option will include an option of 'Return an order' for the user to select.

## Tasks:
- [x] Add a link in the footer to bring the user to the contact form
- [x] In the dropdown choices of the options field of the form, include an option of 'Return an order'
- [x] Ensure the dropdown options are submitting correctly to the admin dashboard
