### ISSUE TITLE
USER STORY: Wishlist

### ISSUE THREAD

**Issue by morganoleary** [morganoleary/Fine-Furnishings#19]
As a **user** I can **view my wishlist** so that **I can easily save any products I want to purchase** . 

## Acceptance Criteria:
- This link will be accessible from the menu ONLY when a user is logged in. 
- This page will list any saved products in the form of a link to the product page. 
- The wishlist will be saved to the user's account and will save the products each time the user logs in or out. 
- The wishlist will be stored on the admin dashboard.

## Tasks:
- [x] If a user is not logged in, implement a message to 'register or login' if they try to add an item to the wishlist
- [x] Create the wishlist template that will store product page links for saved items
- [x] Ensure the products added to the wishlist are saved to the user's profile
- [x] Ensure the admin site is updated with user's wishlist items
