### ISSUE TITLE
USER STORY: Product Searching / Viewing - View list of products

### ISSUE THREAD

**Issue by morganoleary** [morganoleary/Fine-Furnishings#20]
As a **user** I can **view a list of products** so that **I can choose some items to purchase** . 

## Acceptance Criteria:
- The products will be accessible from the menu as well as from blocks on the home page of the site.
- Each product will be able to be selected to take the user to each individual product page.

## Tasks:
- [x] Create furniture category blocks on the home page that will take the user to all selected products.
- [x] Ensure product categories are accessible from the main menu in the navbar.
- [x] Create a link on all products to access each individual product page.
