### ISSUE TITLE
USER STORY: Product Searching / Viewing - View Individual Products

### ISSUE THREAD

**Issue by morganoleary** [morganoleary/Fine-Furnishings#21]
As a **user** I can **view individual product details** so that **I can learn about the product's price, description, dimensions, and see images** . 

## Acceptance Criteria:
- Each product will have a designated page. 
- The product page will include the product name, Sku/ID, price, description, dimensions and image.
- Each product page will allow the user to add items to the wishlist and/or basket to purchase.

## Tasks:
- [x] Create the template for the product page
- [x] Ensure the template includes a place for all product details including: product name, Sku/ID, price, description, dimensions and image
- [x] Add the functionality for the product page to allow user's to add the product to the wishlist and/or basket
