### ISSUE TITLE
USER STORY: Product Searching / Viewing - Search Bar

### ISSUE THREAD

**Issue by morganoleary** [morganoleary/Fine-Furnishings#22]
As a **user** I can **search for products in a search bar** so that **I can quickly find products similar to the keyword searched** . 

## Acceptance Criteria:
- The search bar will be located at the top of the page. 
- The search bar will be available on the home page. 
- The search bar will be available on the product category filtering page(s).

## Tasks:
- [x] Import 'Q' from Django models
- [x] Create a form with a 'GET' request to implement search functionality
- [x] Ensure the search bar is located at the top of the home page and product category filtering pages
