### ISSUE TITLE
USER STORY: Product Searching / Viewing - Filter by Category

### ISSUE THREAD

**Issue by morganoleary** [morganoleary/Fine-Furnishings#23]
As a **user** I can **filter through categories of products** so that **I can narrow down my search and view the company's products** . 

## Acceptance Criteria:
- The product categories will be easily accessible from the navigation menu.
- The main categories will also have a block on the home page to allow the user to start shopping without navigating to the menu.
- The product search page will provide filters available within each main category.
- The categories will include: type of item, size, color & fabric options available.

## Tasks:
- [x] Implement links to product category pages into the menu in the navbar
- [x] Add a block to the home page to allow users to select a main category
- [x] Create filtering within each category using dropdown options
