### ISSUE TITLE
USER STORY: Placing an Order - Add Products to Basket

### ISSUE THREAD

**Issue by morganoleary** [morganoleary/Fine-Furnishings#24]
As a **user** I can **add products to the basket** so that **I can purchase products from the business** . 

## Acceptance Criteria:
- Each product page will provide the option to add an item or multiple items to their basket. 
- The user will be able to navigate to the checkout page through their basket. 
- ONLY registered/logged in users can place an order.
- If a user goes to the checkout page and is not logged in, the user will be prompted to login or sign up if not already.

## Tasks:
- [x] Implement functionality to add and save products to the basket 
- [x] Add a link to checkout on the basket page
- [x] Ensure only logged in users can access the checkout page
- [x] Implement a message to ask the user to log in (if not) when navigating to the checkout page
