### ISSUE TITLE
USER STORY: Placing an Order -  Order Confirmation

### ISSUE THREAD

**Issue by morganoleary** [morganoleary/Fine-Furnishings#25]
As a **user** I can **receive confirmation of an order** so that **I know it was successfully purchased** . 

## Acceptance Criteria:
- Once an order is submitted, confirmation of the order and summary will appear to user. 
- On the order confirmation page, their will be a link to the home page to continue shopping. 
- The order will be reflected in the admin site.

## Tasks:
- [x] Create a template for the order confirmation to appear after order is placed
- [x] Implement a link to the home page on the order confirmation template
- [x] Ensure all order details are reflected on the user's account within the admin dashboard
