### ISSUE TITLE
USER STORY: Placing an Order - Select Product Quantities

### ISSUE THREAD

**Issue by morganoleary** [morganoleary/Fine-Furnishings#26]
As a **user** I can **select a quantity of each product** so that **I can ensure to order the correct number of items** . 

## Acceptance Criteria:
- Each individual product page will provide the option to increase or decrease the quantity before adding to the basket.
- The basket will include the option on each product added to increase or decrease the quantities before checking out.

## Tasks:
- [x] Implement functionality for the quantity of a product to be increased with a '+' and decreased with a '-' on each product page
- [x] Implement functionality for the quantity of each product within the basket to be increased with a '+' and decreased with a '-'
- [x] Ensure the minimum quantity selected is '1'
