### ISSUE TITLE
USER STORY: Placing an Order - Order History

### ISSUE THREAD

**Issue by morganoleary** [morganoleary/Fine-Furnishings#27]
As a **returning visitor** I can **access my order history** so that **I can view previous purchases** . 

## Acceptance Criteria:
- The user should be able to access their order history through the main menu ONLY when logged in.
- The order history should include: order number, date of purchase, products ordered & the order total.
- Each order placed should be reflected in the specific user's profile on the admin site.
- The order confirmation will be emailed to the customer upon successful ordering. 

## Tasks:
- [x] A link to the 'order history' page will be accessible from the menu ONLY when a user is logged in
- [x] Ensure the user's purchase is saved to their profile in 'order history' on the admin dashboard
- [x] Ensure saved to the user's order history include: order number, date of purchase, products ordered & the order total
- [x] Create the email text files & web-hook handlers to send confirmation emails to users
