### ISSUE TITLE
USER STORY: Frequently Asked Questions

### ISSUE THREAD

**Issue by morganoleary** [morganoleary/Fine-Furnishings#28]
As a **first time user** I can **see the business' FAQs** so that **I can find out more before placing an order** . 

## Acceptance Criteria:
- This link will be accessible in the footer on all pages.
- This link will take the user to a separate page that lists previous user's frequently asked questions.
- This page will also include a link to the contact page form so the user can submit a new query to the business.

## Tasks:
- [x] Add a link to the footer to the FAQs page
- [x] Create an FAQ template displaying questions and answers
- [x] Implement a link to the contact page form in the FAQs template page
