### ISSUE TITLE
USER STORY: Social Media

### ISSUE THREAD

**Issue by morganoleary** [morganoleary/Fine-Furnishings#29]
As a **user** I can **visit the business' social media sites** so that **I can find out more to connect with the company** . 

## Acceptance Criteria:
- The social media links will be accessible in the footer on all pages.
- There will be a link for Facebook & Instagram.
- These links will open the social media sites in a separate window. 

## Tasks:
- [x] Utilize favicons within the footer to create links to social media sites
- [x] Ensure each social media link opens in a separate window
- [x] Add links to Facebook & Instagram
