### ISSUE TITLE
USER STORY: Site Navigation - Social Media

### ISSUE THREAD

**Issue by morganoleary** [morganoleary/Fine-Furnishings#3]
As a **first time user** I can **click on the business' social media links** so that **I can further research the business and connect** . 

## Acceptance Criteria:
- Social media links should be easily found in the footer. 
- The links will open a new web page to the social media site.

## Tasks:
- [x] Create a Facebook page for business
- [x] Add social media links to footer
- [x] Set attribute target="_blank" to open links in new tab
