### ISSUE TITLE
USER STORY: Company Reviews

### ISSUE THREAD

**Issue by morganoleary** [morganoleary/Fine-Furnishings#30]
As a **user** I can **view reviews of the business** so that **I can make an informed decision before placing an order** . 

## Acceptance Criteria:
- There will be a link to Trustpilot in the footer on all pages.
- This link will open the site in a separate window.

## Tasks:
- [ ] Utilize favicons to add a link to Trustpilot in the footer
- [ ] Ensure the footer is accessible on all pages of the site
- [ ] Ensure the link opens in a new window
