### ISSUE TITLE
ADMIN: Product CRUD Functionality

### ISSUE THREAD

**Issue by morganoleary** [morganoleary/Fine-Furnishings#32]
As an **administrator of the site** I can **create, read, update & delete products on the website** so that **I can easily manage products when logged in to the site** . 

## Acceptance Criteria:
- Only logged in admin users have access to the product CRUD functionality on the site.
- The admin should have the option to add a product to the site
- Each product should have an 'Edit' & 'Delete' option
- Editing a product should allow the admin to edit the following: product_id, name, description, categories, dimensions (height, width, depth), price, image, and bedframe size if applicable

## Tasks:
- [x] Add a product management link to navigation menu for logged in admin/superuser
- [x] Create views for add, edit and delete product options
- [x] Create templates for add and edit product options
- [x] Create URLs for add_product, edit_product, delete_product
- [x] Add edit & delete buttons on product cards and on product detail pages
- [x] Add success messages throughout functionality
- [x] Add a confirmation modal before deleting a product for defensive design purposes
