### ISSUE TITLE
USER STORY: Site Navigation - FAQs Page

### ISSUE THREAD

**Issue by morganoleary** [morganoleary/Fine-Furnishings#4]
As a **user** I can **easily find the companies FAQs** so that **I can find out more about their services** . 

## Acceptance Criteria:
- This page can be found from a link in the footer.
- The FAQs will bring the user to a separate page to read all the facts about the company.
- This page will have a link to the contact page form to ask further questions.

## Tasks:
- [x] Create FAQ template
- [x] Add link to footer to take user to the FAQ page
- [x] On the FAQ page, add a link to take the user to the 'Contact Us' form
