### ISSUE TITLE
USER STORY: Site Navigation - About Us page

### ISSUE THREAD

**Issue by morganoleary** [morganoleary/Fine-Furnishings#5]
As a **first time user** I can **easily find an information page** so that **I can learn more about the business** . 

## Acceptance Criteria:
- A link to the 'About Us' page will be accessible from the footer on all pages.
- This page will include details about the business including: photo(s), summary & link to the FAQs page.

## Tasks:
- [ ] Create a template for an About Us page
- [ ] Include photo of business & summary of company on the 'About Us' page
- [ ] On the 'About Us' page, include a link to the FAQ page
- [ ] Add link to the 'About Us' page in the footer
