### ISSUE TITLE
USER STORY: User Account - Register

### ISSUE THREAD

**Issue by morganoleary** [morganoleary/Fine-Furnishings#6]
As a **first time user** I can **register a new account** so that **I can place an order** . 

## Acceptance Criteria:
- The register/sign up button will be visible in the menu if a user is not logged in.
- Registration details will require: Username & Password (Django AllAuth)
- Once registered, the user will receive a success message and will be rerouted to the home page to start shopping. 

## Tasks:
- [x] Set up Django AllAuth 
- [x] Display a "Register" button in the menu - only if a user is not logged in 
- [x] Ensure user's menu options change after being logged in
- [x] Ensure that user registrations are recorded and displayed on the admin dashboard
- [x] Redirect the user to the home page once registered & logged in
