### ISSUE TITLE
USER STORY: User Account - Wishlist

### ISSUE THREAD

**Issue by morganoleary** [morganoleary/Fine-Furnishings#7]
As a **first time user** I can **create an account** so that **I can start a wishlist of products I would like to buy** . 

## Acceptance Criteria:
- The register/sign up button will be visible in the menu if a user is not logged in.
- Once signed up & logged in the user will have the option to navigate to their wishlist from the menu. 
- In the wishlist, they will receive a message that the wishlist is empty with a link to 'start shopping', that will take them to the home page.
- The wishlist will be populated by a user clicking on a 'heart' icon next to each product.

## Tasks:
- [ ] Display a "Register" & "Login" button in the menu - only if a user is not logged in
- [ ] Ensure user's menu options change after being logged in
- [ ] Once logged in, display a "Wishlist" button in the menu
- [ ] When the wishlist is empty, display a message and provide a link to the home page, 'start shopping'
