### ISSUE TITLE
USER STORY: User Account - Order History

### ISSUE THREAD

**Issue by morganoleary** [morganoleary/Fine-Furnishings#8]
As a **returning visitor** I can **login to my account** so that **I can see my order history.** . 

## Acceptance Criteria:
- Order history will be saved on the user's profile in the admin site.
- A login button should be easily accessible to the user within the menu bar.
- When clicked, the user will be given the option to login with an existing username and password.
- Once logged in, the user will be directed to the home page.
- Once logged in, the menu will then an "Order History" option to the user.
- By clicking on order history, the user will be taken to a separate page to see all previous purchases and details.
- If there is no previous order a message will appear with 'no orders placed yet' and will provide a link to 'start shopping'.
- When a user account is deleted, the order history will remain in the admin site.

## Tasks:
- [x] Display a login button in the menu if their is no user logged in
- [x] Redirect user to the home page once logged in
- [x] Ensure the menu options change once a user is logged in to provide an "Order History" button
- [x] The order history page will display an order history details including: order number, order date, items ordered, order total
- [x] If no orders place, display a message of 'no previous orders' & provide a link to 'start shopping'
- [x] Ensure Order History is saved on the users account
- [x] Ensure order history is saved even when a user deletes the account
