### ISSUE TITLE
USER STORY: User Account - Personal Details

### ISSUE THREAD

**Issue by morganoleary** [morganoleary/Fine-Furnishings#9]
As a **returning visitor** I can **login to my account** so that **I can update my personal details** . 

## Acceptance Criteria:
- Once logged in, the user will be directed to the home page & the menu options will change.
- The "Personal Details" page will be easily accessible from the menu where they will be able to view their personal details. 
- By clicking on "Personal Details", the user will be taken to a separate page with their personal details form. 
- Any current personal details will auto-populate and an edit button will be available to update and save any changes.
- Changes to the profile should be reflected across the site.

## Tasks:
- [x] Ensure the menu options change when a user is logged in
- [x] Create a form to hold the user's personal details
- [x] Implement an edit button to update changes
- [x] Implement a save button to save any changes made
- [x] Ensure the user's personal details are updated on the admin site & save to the user's account profile
